# EPISTEMIC FORMATIVES AND MODALS 
# the speakers’ degree of certainty about the stated proposition and their level of assurance (assertability), but they are not correlated with the scale of remoteness of a given event.
# \cite{mihas2012spatial[p. 14]

define MODAL=FORMATIVE [
  (PRNO) 
| (V=S=OPT) 
| (V=S=CNTF) 
| (V=S=O) (PRNO) (V=S=OPT)  
| (V=S=O) (PRNO) (V=S=DUB) 
| (V=S=O) (PRNO) 
| (V=S=O) (PRNO) (V=S=REL) (V=S=Q) 
];
